Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-08, with the labels that each got.

#277 manage account page - fixed css and moved rating
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/styles.css
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#278 fixed issue with menu-bar when refreshing
  apps/office-booker/src/app/cognito.service.ts
Labels: Priority: High, Type: Fix, Status: Ready

#282 Changed appearance of map bookings
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Medium, Status: Busy, Type: Change, Type: Cosmetic

#279 Various changes
  apps/office-booker/src/app/app.component.css
  apps/office-booker/src/app/app.component.html
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
Labels: Priority: Medium, Type: Feature, Type: Fix, Status: Ready

#285 Feature/default time
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Type: Enhance, Priority: Low, Status: Needs-tests

#286 Feature/date validation
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Type: Enhance, Priority: Low, Status: Needs-tests

#288 Changes/brett
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/landing-page/landing-page.component.css
  apps/office-booker/src/app/landing-page/landing-page.component.html
  apps/office-booker/src/app/landing-page/landing-page.component.spec.ts
  apps/office-booker/src/app/landing-page/landing-page.component.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Cosmetic, Status: Not-ready

#290 Cosmetic/map snackbar
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/styles.css
Labels: Priority: Medium, Type: Cosmetic, Status: Needs-tests

#291 Feature/snackbars
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.css
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#292 Feature/desk info on hover
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Status: Busy, Type: Feature

#293 Fixed misalignment issue
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Status: Busy, Type: Cosmetic, Type: Feature

#294 Feature/own booking
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Type: Enhance, Priority: Low, Status: Needs-tests

#297 Feature/change facility schema
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
  prisma/migrations/20220821195907_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Type: Enhance, Priority: Medium, Status: Ready

#299 Feature/desk info on hover
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Priority: Medium, Status: Busy, Type: Feature

#295 profile page and list of invited to meetings
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.css
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.html
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
Labels: Priority: High, Type: Cosmetic, Type: Feature, Status: Ready

#300 removed unecessary svg tags
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
Labels: Priority: Low, Type: Fix, Status: Ready

#306 Generated office maker component
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/directives/draggable.directive.spec.ts
  apps/office-booker/src/app/directives/draggable.directive.ts
  apps/office-booker/src/app/directives/droppable.directive.spec.ts
  apps/office-booker/src/app/directives/droppable.directive.ts
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.spec.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/svg.service.spec.ts
  apps/office-booker/src/app/services/svg.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: High, Status: Busy, Type: Feature

#305 fixed issues with chips not functioning correctly
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.css
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.html
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
Labels: Priority: Medium, Type: Fix, Status: Ready
