Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-05, with the labels that each got.

#10 add badges to represent open issues and prs
  README.md
Labels: Priority : High

#17 add prisma as dependency
  .env
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: Priority: High, Type: Feature, Status: Ready

#22 add docker-compose.yml for mongodb_docker
  .env
  docker-compose.yml
Labels: Priority: High, Type: Feature, Status: Ready

#24 Add basic prisma models
  .env
  docker-compose.yml
  package.json
  prisma/migrations/20220510185752_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  yarn.lock
Labels: Priority: Medium, Type: Feature, Status: Ready

#23 Added CI/CD tests
  .github/workflows/index.yml
  .github/workflows/nxtest.yml
Labels: Type: Enhance, Priority: High, Status: Ready

#25 Add some basic stuff to handle bookings
  angular.json
  libs/api/bookings/repository/data-access/.eslintrc.json
  libs/api/bookings/repository/data-access/README.md
  libs/api/bookings/repository/data-access/jest.config.ts
  libs/api/bookings/repository/data-access/project.json
  libs/api/bookings/repository/data-access/src/index.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.module.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  libs/api/bookings/repository/data-access/tsconfig.json
  libs/api/bookings/repository/data-access/tsconfig.lib.json
  libs/api/bookings/repository/data-access/tsconfig.spec.json
  libs/api/shared/services/prisma/data-access/.eslintrc.json
  libs/api/shared/services/prisma/data-access/README.md
  libs/api/shared/services/prisma/data-access/jest.config.ts
  libs/api/shared/services/prisma/data-access/project.json
  libs/api/shared/services/prisma/data-access/src/index.ts
  libs/api/shared/services/prisma/data-access/src/lib/api-shared-services-prisma-data-access.module.ts
  libs/api/shared/services/prisma/data-access/src/lib/api-shared-services-prisma-data-access.service.spec.ts
  libs/api/shared/services/prisma/data-access/src/lib/api-shared-services-prisma-data-access.service.ts
  libs/api/shared/services/prisma/data-access/tsconfig.json
  libs/api/shared/services/prisma/data-access/tsconfig.lib.json
  libs/api/shared/services/prisma/data-access/tsconfig.spec.json
  prisma/migrations/20220510200333_init/migration.sql
  prisma/schema.prisma
  tsconfig.base.json
Labels: Priority: Medium, Type: Feature, Status: Ready

#28 Feature/view booking
  apps/api/project.json
  apps/office-booker-e2e/project.json
  apps/office-booker-e2e/src/integration/app.spec.ts
  apps/office-booker/project.json
  apps/office-booker/src/app/app.component.html
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/bookings.component.css
  apps/office-booker/src/app/bookings/bookings.component.html
  apps/office-booker/src/app/bookings/bookings.component.spec.ts
  apps/office-booker/src/app/bookings/bookings.component.ts
  apps/office-booker/src/index.html
  apps/office-booker/src/styles.css
  libs/api-interfaces/project.json
  libs/api/bookings/repository/data-access/project.json
  libs/api/shared/services/prisma/data-access/project.json
  package.json
  yarn.lock
Labels: Priority: Medium, Type: Feature, Status: Needs-tests

#29 persist the postgres db in the container
  docker-compose.yml
Labels: Type: Enhance, Priority: Low, Status: Ready

#32 Create data-access services for rooms, desks and facilities
  angular.json
  libs/api/desks/repository/data-access/.eslintrc.json
  libs/api/desks/repository/data-access/README.md
  libs/api/desks/repository/data-access/jest.config.ts
  libs/api/desks/repository/data-access/project.json
  libs/api/desks/repository/data-access/src/index.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.module.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.spec.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
  libs/api/desks/repository/data-access/tsconfig.json
  libs/api/desks/repository/data-access/tsconfig.lib.json
  libs/api/desks/repository/data-access/tsconfig.spec.json
  libs/api/facilities/repository/data-access/.eslintrc.json
  libs/api/facilities/repository/data-access/README.md
  libs/api/facilities/repository/data-access/jest.config.ts
  libs/api/facilities/repository/data-access/project.json
  libs/api/facilities/repository/data-access/src/index.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.module.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.ts
  libs/api/facilities/repository/data-access/tsconfig.json
  libs/api/facilities/repository/data-access/tsconfig.lib.json
  libs/api/facilities/repository/data-access/tsconfig.spec.json
  libs/api/rooms/repository/data-access/.eslintrc.json
  libs/api/rooms/repository/data-access/README.md
  libs/api/rooms/repository/data-access/jest.config.ts
  libs/api/rooms/repository/data-access/project.json
  libs/api/rooms/repository/data-access/src/index.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.module.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.spec.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.ts
  libs/api/rooms/repository/data-access/tsconfig.json
  libs/api/rooms/repository/data-access/tsconfig.lib.json
  libs/api/rooms/repository/data-access/tsconfig.spec.json
  tsconfig.base.json
Labels: Priority: High, Type: Feature, Status: Not-ready

#42 added codecov stuff and badges
  .github/workflows/nxtest.yml
  README.md
Labels: Type: Enhance, Priority: Medium, Status: Needs-tests

#43 Added script to merge code coverage files
  tools/scripts/merge-report.js
Labels: Type: Enhance, Priority: High, Status: Ready

#44 fixed the path for merge script
  .github/workflows/nxtest.yml
Labels: Priority: Medium, Type: Fix, Status: Ready

#45 Corrected spelling mistake
  .github/workflows/nxtest.yml
Labels: Priority: Medium, Type: Fix, Status: Ready

#34 Add controllers to access the data via a rest api
  .github/workflows/nxtest.yml
  angular.json
  apps/api/src/app/app.module.ts
  libs/api/desks/api/.eslintrc.json
  libs/api/desks/api/README.md
  libs/api/desks/api/jest.config.ts
  libs/api/desks/api/project.json
  libs/api/desks/api/src/index.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.spec.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/api/src/lib/api-desks-api.module.ts
  libs/api/desks/api/tsconfig.json
  libs/api/desks/api/tsconfig.lib.json
  libs/api/desks/api/tsconfig.spec.json
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
  libs/api/facilities/api/.eslintrc.json
  libs/api/facilities/api/README.md
  libs/api/facilities/api/jest.config.ts
  libs/api/facilities/api/project.json
  libs/api/facilities/api/src/index.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.spec.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/facilities/api/src/lib/api-facilities-api.module.ts
  libs/api/facilities/api/tsconfig.json
  libs/api/facilities/api/tsconfig.lib.json
  libs/api/facilities/api/tsconfig.spec.json
  libs/api/rooms/api/.eslintrc.json
  libs/api/rooms/api/README.md
  libs/api/rooms/api/jest.config.ts
  libs/api/rooms/api/project.json
  libs/api/rooms/api/src/index.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.spec.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.ts
  libs/api/rooms/api/src/lib/api-rooms-api.module.ts
  libs/api/rooms/api/tsconfig.json
  libs/api/rooms/api/tsconfig.lib.json
  libs/api/rooms/api/tsconfig.spec.json
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.ts
  tsconfig.base.json
Labels: Priority: High, Type: Feature, Status: Ready

#46 Fixed filepath
  .github/workflows/nxtest.yml
Labels: Priority: Medium, Type: Fix, Status: Not-ready

#47 add bookings rest api via its controller
  angular.json
  apps/api/src/app/app.module.ts
  apps/api/src/main.ts
  libs/api/bookings/api/.eslintrc.json
  libs/api/bookings/api/README.md
  libs/api/bookings/api/jest.config.ts
  libs/api/bookings/api/project.json
  libs/api/bookings/api/src/index.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/api/src/lib/api-bookings-api.module.ts
  libs/api/bookings/api/tsconfig.json
  libs/api/bookings/api/tsconfig.lib.json
  libs/api/bookings/api/tsconfig.spec.json
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Priority: High, Status: Busy, Type: Feature, Status: Needs-info

#52 Modify desk schema
  prisma/migrations/20220510185752_init/migration.sql
  prisma/migrations/20220510200333_init/migration.sql
  prisma/migrations/20220511210106_init/migration.sql
  prisma/schema.prisma
Labels: Type: Enhance, Priority: Low, Status: Ready

#59 Update README.md
  README.md
Labels: Type: Documentation, Priority: High, Status: Busy

#60 Update README.md
  README.md
Labels: Type: Documentation, Priority: Medium, Status: Busy

#61 Update README.md
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#65 ✨ (menu component): Added menu component for use
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/menu-bar/menu-bar.component.spec.ts
  apps/office-booker/src/app/menu-bar/menu-bar.component.ts
Labels: Priority: Low, Type: Feature, Status: Ready

#64 Update README.md
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#66 Added menubar and fix to metatest
  .github/workflows/metatests.yml
  apps/office-booker/src/app/app.component.html
  apps/office-booker/src/app/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/menu-bar/menu-bar.component.ts
Labels: Priority: Medium, Type: Cosmetic, Status: Ready

#67 Add prisma seeding
  package.json
  prisma/seed.ts
  yarn.lock
Labels: Type: Enhance, Priority: Medium, Status: Ready

#62 Added styling for Grid
  apps/office-booker/src/app/bookings/bookings.component.css
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#69 Updated menu-bar names
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#76 Fix Damian's LinkedIn
  README.md
Labels: Priority: Low, Type: Chore, Status: Ready

#77 Added Icons to Menu
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Change, Status: Ready

#78 Menu final icons added with last field
  apps/office-booker/src/app/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Change, Type: Cosmetic, Status: Ready

#79 Finish bookings component for demo 1
  apps/office-booker/src/app/bookings/bookings.component.css
  apps/office-booker/src/app/bookings/bookings.component.html
  apps/office-booker/src/app/bookings/bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Priority: High, Type: Feature, Status: Ready

#80 Update README.md video link
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#81 Added unit testing for main booking component
  apps/office-booker/src/app/bookings/bookings.component.spec.ts
Labels: Priority: Medium, Type: Chore, Type: Test, Status: Ready

#85 Added a login component and setup routing
  apps/office-booker/src/app/app.component.html
  apps/office-booker/src/app/app.component.spec.ts
  apps/office-booker/src/app/app.component.ts
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/app.routing.ts
  apps/office-booker/src/app/login/login.component.css
  apps/office-booker/src/app/login/login.component.html
  apps/office-booker/src/app/login/login.component.spec.ts
  apps/office-booker/src/app/login/login.component.ts
  apps/office-booker/src/app/menu-bar/menu-bar.component.html
Labels: Priority: Medium, Status: Busy, Type: Feature

#97 Added test for ApiBookingsRepositoryDataAccessService
  libs/api/bookings/api/tsconfig.json
  libs/api/bookings/repository/data-access/src/client.ts
  libs/api/bookings/repository/data-access/src/functions.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/bookings/repository/data-access/src/singleton.ts
  package.json
  yarn.lock
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#101 Feature/booking manager
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Change, Status: Ready

#99 Feature/testingUnit tests for ApiDesksRepositoryDataAccessService
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.spec.ts
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#102 Added mat cards import and created a template for bookings
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
Labels: Priority: Low, Status: Busy, Type: Feature, Status: Not-ready

#103 Unit test for ApiFacilitiesRepositoryDataAccessService
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#105 🎨 (component): Addition of booking-card component
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.css
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.html
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
Labels: Type: Enhance, Priority: Low, Status: Not-ready

#106 mock data for the manage bookings
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
Labels: Priority: Low, Status: Busy, Type: Change

#107 registration page and other fixes
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/app.routing.ts
  apps/office-booker/src/app/registration/registration.component.css
  apps/office-booker/src/app/registration/registration.component.html
  apps/office-booker/src/app/registration/registration.component.spec.ts
  apps/office-booker/src/app/registration/registration.component.ts
  nx.json
  prisma/schema.prisma
Labels: Priority: Medium, Type: Feature

#111 Unit test for ApiRoomsRepositoryDataAccessService
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.spec.ts
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#109 Added default routing to login page
  apps/office-booker/src/app/app.module.ts
Labels: Priority: Low, Type: Change, Status: Ready

#116 Add companies and users
  angular.json
  apps/api/src/app/app.module.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  libs/api/companies/api/.eslintrc.json
  libs/api/companies/api/README.md
  libs/api/companies/api/jest.config.ts
  libs/api/companies/api/project.json
  libs/api/companies/api/src/index.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.spec.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
  libs/api/companies/api/src/lib/api-companies-api.module.ts
  libs/api/companies/api/tsconfig.json
  libs/api/companies/api/tsconfig.lib.json
  libs/api/companies/api/tsconfig.spec.json
  libs/api/companies/repository/data-access/.eslintrc.json
  libs/api/companies/repository/data-access/README.md
  libs/api/companies/repository/data-access/jest.config.ts
  libs/api/companies/repository/data-access/project.json
  libs/api/companies/repository/data-access/src/index.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.module.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.spec.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.ts
  libs/api/companies/repository/data-access/tsconfig.json
  libs/api/companies/repository/data-access/tsconfig.lib.json
  libs/api/companies/repository/data-access/tsconfig.spec.json
  libs/api/users/api/.eslintrc.json
  libs/api/users/api/README.md
  libs/api/users/api/jest.config.ts
  libs/api/users/api/project.json
  libs/api/users/api/src/index.ts
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/api/src/lib/api-users-api.module.ts
  libs/api/users/api/tsconfig.json
  libs/api/users/api/tsconfig.lib.json
  libs/api/users/api/tsconfig.spec.json
  libs/api/users/repository/data-access/.eslintrc.json
  libs/api/users/repository/data-access/README.md
  libs/api/users/repository/data-access/jest.config.ts
  libs/api/users/repository/data-access/project.json
  libs/api/users/repository/data-access/src/index.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.module.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
  libs/api/users/repository/data-access/tsconfig.json
  libs/api/users/repository/data-access/tsconfig.lib.json
  libs/api/users/repository/data-access/tsconfig.spec.json
  prisma/migrations/20220529160443_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  tsconfig.base.json
Labels: Type: Enhance, Priority: High, Status: Busy

#117 Logic with dummy data for displaying bookings
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.html
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
Labels: Priority: Medium, Status: Busy, Type: Feature, Status: Not-ready

#121 fixed the logic and improved the template
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.html
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
Labels: Priority: Low, Status: Busy, Type: Feature, Status: Not-ready

#120 login and registration pages using aws-cognito
  angular.json
  apps/office-booker/project.json
  apps/office-booker/src/app/app.component.ts
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.spec.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/registration/registration.component.css
  apps/office-booker/src/app/registration/registration.component.html
  apps/office-booker/src/app/registration/registration.component.ts
  apps/office-booker/src/environments/environment.prod.ts
  apps/office-booker/src/environments/environment.ts
  apps/office-booker/src/main.ts
  apps/office-booker/src/polyfills.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Priority: Medium, Type: Feature, Status: Ready

#124 Added unit tests for ApiDesksApiController and ApiBookingsApiController
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.spec.ts
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#125 Fixed test for createBooking method in ApiBookingsController
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
Labels: Priority: Medium, Status: Busy, Type: Chore, Type: Test

#126 Change/map change svg
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
Labels: Priority: Medium, Type: Change, Type: Feature, Status: Needs-tests
