Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-07, with the labels that each got.

#183 Few cosmetic changes on various pages
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/styles.css
Labels: Priority: Medium, Type: Cosmetic, Status: On-hold

#184 Feature/adding comments
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/assets/background-image.png
Labels: Priority: Low, Type: Chore, Status: Not-ready

#185 function to delete user
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Priority: Medium, Type: Feature, Status: Ready

#189 Fixes for various issues and some changes
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.spec.ts
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/authentication/forgot-password/forgot-password.component.css
  apps/office-booker/src/app/authentication/forgot-password/forgot-password.component.html
  apps/office-booker/src/app/authentication/forgot-password/forgot-password.component.spec.ts
  apps/office-booker/src/app/authentication/forgot-password/forgot-password.component.ts
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.spec.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.css
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.html
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Type: Bug, Priority: Medium, Status: Busy, Type: Feature

#191 Add user ratings
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
  prisma/migrations/20220722094350_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Type: Enhance, Priority: High, Status: Ready

#194 Feature/desk meeting rooms
  prisma/migrations/20220609104623_init/migration.sql
  prisma/migrations/20220722094350_init/migration.sql
  prisma/migrations/20220722104249_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Type: Enhance, Priority: High, Status: Ready

#195 deleted leftover migrations and changed registration page
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  prisma/migrations/20220718150816_office_booker/migration.sql
  prisma/migrations/20220718155242_mig/migration.sql
  prisma/migrations/20220720112838_mig/migration.sql
  prisma/seed.ts
Labels: Type: Bug, Priority: Medium, Status: Ready

#197 Fixed problem where guest could invite others
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  prisma/seed.ts
Labels: Priority: High, Type: Feature, Status: Ready

#201 updated initial guest value to correctly show up
  apps/office-booker/src/app/cognito.service.ts
Labels: Priority: Low, Type: Fix, Status: Ready

#204 Updates to guest registration page
  apps/office-booker/src/app/authentication/guest/guest.component.css
  apps/office-booker/src/app/authentication/guest/guest.component.html
  apps/office-booker/src/app/authentication/guest/guest.component.spec.ts
  apps/office-booker/src/app/authentication/guest/guest.component.ts
Labels: Priority: Medium, Type: Cosmetic, Type: Fix, Status: On-hold

#206 Added checks to prevent duplicate guest invites
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
Labels: Type: Enhance, Priority: Low, Status: Busy

#210 Invites backend
  apps/office-booker/src/app/services/booking-service.service.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  prisma/migrations/20220725160329_/migration.sql
  prisma/schema.prisma
Labels: Priority: High, Type: Feature, Status: Ready

#208 Feature/guests: Added email service
  .env
  angular.json
  apps/api/project.json
  apps/api/src/app/app.module.ts
  apps/office-booker-e2e/project.json
  apps/office-booker/project.json
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  libs/api-interfaces/project.json
  libs/api/bookings/repository/data-access/project.json
  libs/api/mail/.eslintrc.json
  libs/api/mail/README.md
  libs/api/mail/jest.config.ts
  libs/api/mail/project.json
  libs/api/mail/src/index.ts
  libs/api/mail/src/lib/mail.module.ts
  libs/api/mail/src/lib/mail.service.ts
  libs/api/mail/src/lib/mail.spec.ts
  libs/api/mail/tsconfig.json
  libs/api/mail/tsconfig.lib.json
  libs/api/mail/tsconfig.spec.json
  libs/api/shared/services/prisma/data-access/project.json
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Type: Enhance, Priority: Medium, Status: Busy, Type: Feature

#205 Reusable popup-dialog
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/guest-login/guest-login.component.css
  apps/office-booker/src/app/authentication/guest/guest.component.css
  apps/office-booker/src/app/authentication/guest/guest.component.html
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.css
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.html
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.spec.ts
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.css
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/popup-dialog/popup-dialog.component.css
  apps/office-booker/src/app/shared/popup-dialog/popup-dialog.component.html
  apps/office-booker/src/app/shared/popup-dialog/popup-dialog.component.spec.ts
  apps/office-booker/src/app/shared/popup-dialog/popup-dialog.component.ts
  apps/office-booker/src/app/shared/popup-dialog/popup-dialog.service.ts
Labels: Priority: Medium, Type: Feature, Status: On-hold

#214 Added confirmation pop up to the guest invite system
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
Labels: Type: Enhance, Priority: Low, Status: Ready

#216 Improvements to guest invites
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  libs/api/mail/src/lib/mail.service.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
Labels: Type: Enhance, Priority: Low, Status: Ready

#221 Feature/invite guests: Added email validity check
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
Labels: Type: Enhance, Priority: Low, Status: Ready

#223 Feature/voting
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/guest/guest.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.css
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: High, Type: Feature, Status: Ready

#228 Feature/office wide schedule view
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: High, Type: Feature, Status: Needs-tests

#218 Invite others to meeting rooms
  apps/office-booker/src/app/app.component.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.css
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  apps/office-booker/src/styles.css
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
Labels: Priority: High, Type: Feature, Status: Ready

#229 Added popup for when user add review
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
Labels: Priority: Low, Type: Feature, Status: Ready

#234 Fixed bug - duplicate booking
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Type: Bug, Priority: Medium, Type: Fix, Status: Ready

#232 declining Invites
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/assets/background.svg
  apps/office-booker/src/styles.css
Labels: Priority: High, Type: Feature, Status: Ready

#235 Shows the type of user logged in
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  apps/office-booker/src/styles.css
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#236 Css/compare bookings
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Type: Change, Status: Needs-tests

#239 Docker container stuff
  apps/api/Dockerfile
  apps/api/jest.config.ts
  apps/api/project.json
  apps/office-booker-e2e/project.json
  apps/office-booker/Dockerfile
  apps/office-booker/jest.config.ts
  apps/office-booker/project.json
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/tsconfig.json
  docker-compose.yml
  jest.config.ts
  jest.preset.js
  libs/api-interfaces/project.json
  libs/api/authorization/jest.config.ts
  libs/api/authorization/project.json
  libs/api/bookings/api/jest.config.ts
  libs/api/bookings/api/project.json
  libs/api/bookings/repository/data-access/jest.config.ts
  libs/api/bookings/repository/data-access/project.json
  libs/api/companies/api/jest.config.ts
  libs/api/companies/api/project.json
  libs/api/companies/repository/data-access/jest.config.ts
  libs/api/companies/repository/data-access/project.json
  libs/api/desks/api/jest.config.ts
  libs/api/desks/api/project.json
  libs/api/desks/repository/data-access/jest.config.ts
  libs/api/desks/repository/data-access/project.json
  libs/api/facilities/api/jest.config.ts
  libs/api/facilities/api/project.json
  libs/api/facilities/repository/data-access/jest.config.ts
  libs/api/facilities/repository/data-access/project.json
  libs/api/mail/project.json
  libs/api/permissions/jest.config.ts
  libs/api/permissions/project.json
  libs/api/rooms/api/jest.config.ts
  libs/api/rooms/api/project.json
  libs/api/rooms/repository/data-access/jest.config.ts
  libs/api/rooms/repository/data-access/project.json
  libs/api/shared/services/prisma/data-access/jest.config.ts
  libs/api/shared/services/prisma/data-access/project.json
  libs/api/users/api/jest.config.ts
  libs/api/users/api/project.json
  libs/api/users/repository/data-access/jest.config.ts
  libs/api/users/repository/data-access/project.json
  migrations.json
  nx.json
  package.json
  yarn.lock
Labels: Priority: High, Type: Feature, Status: On-hold

#237 🐛 (bookings): guest multi booking, cancel booking
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Type: Fix, Status: Needs-tests

#241 Add build script and use hosted db
  .env
  apps/api/Dockerfile
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/environments/environment.prod.ts
  apps/office-booker/src/environments/environment.ts
  build.sh
Labels: Type: Enhance, Priority: High, Status: Ready

#242 Patch/meeting room
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  prisma/seed.ts
Labels: Priority: Medium, Type: Cosmetic, Status: Needs-tests

#243 🩹 (compare): comparison show correct type
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
Labels: Priority: Medium, Type: Fix, Status: Needs-tests

#244 Patch/ratings
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
Labels: Priority: Low, Type: Fix, Status: Needs-tests

#245 Patch/email invite
  libs/api/mail/src/lib/mail.service.ts
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#246 Update README.md
  README.md
Labels: Type: Documentation, Priority: High, Status: Ready

#248 Update README.md
  README.md
Labels: Type: Documentation, Priority: High, Status: Ready

#249 Update README.md
  README.md
Labels: Type: Bug, Priority: Low, Type: Feature, Status: Needs-info
