Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-09, with the labels that each got.

#310 Changed the SVGs to rectangles
  apps/office-booker/src/app/directives/draggable.directive.ts
  apps/office-booker/src/app/directives/droppable.directive.ts
  apps/office-booker/src/app/office-maker/office-maker.component.html
Labels: Priority: Medium, Status: Busy, Type: Feature

#311 Profile page
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Priority: Medium, Type: Feature, Status: On-hold

#312 changes to accounts page
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.css
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Priority: Medium, Type: Feature, Status: Ready

#314 Floor selector on map-bookings page
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Priority: High, Type: Feature, Status: Ready

#315 tried to use mat-toolbar for options
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#318 Feature/save map
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.spec.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/office-maker.service.spec.ts
  apps/office-booker/src/app/services/office-maker.service.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
Labels: Type: Enhance, Priority: High, Type: Feature, Status: Needs-tests

#316 Password reset alerts and prisma schema change for emails in companies
  apps/office-booker/src/app/authentication/account/account.component.html
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.spec.ts
  prisma/migrations/20220912085204_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Priority: Medium, Type: Feature, Status: Ready

#320 Basic text input to change size of office maker items
  .env
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
Labels: Type: Enhance, Priority: High, Status: Busy, Type: Feature

#321 Made booking map zoomable and scrollable
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Status: Busy, Type: Feature

#325 Add walls
  angular.json
  apps/api/src/app/app.module.ts
  libs/api/walls/api/.babelrc
  libs/api/walls/api/.eslintrc.json
  libs/api/walls/api/README.md
  libs/api/walls/api/jest.config.ts
  libs/api/walls/api/project.json
  libs/api/walls/api/src/index.ts
  libs/api/walls/api/src/lib/api-walls-api.controller.spec.ts
  libs/api/walls/api/src/lib/api-walls-api.controller.ts
  libs/api/walls/api/src/lib/api-walls-api.module.ts
  libs/api/walls/api/tsconfig.json
  libs/api/walls/api/tsconfig.lib.json
  libs/api/walls/api/tsconfig.spec.json
  libs/api/walls/data-access/.babelrc
  libs/api/walls/data-access/.eslintrc.json
  libs/api/walls/data-access/README.md
  libs/api/walls/data-access/jest.config.ts
  libs/api/walls/data-access/project.json
  libs/api/walls/data-access/src/index.ts
  libs/api/walls/data-access/src/lib/api-walls-data-access.module.ts
  libs/api/walls/data-access/src/lib/api-walls-data-access.service.spec.ts
  libs/api/walls/data-access/src/lib/api-walls-data-access.service.ts
  libs/api/walls/data-access/tsconfig.json
  libs/api/walls/data-access/tsconfig.lib.json
  libs/api/walls/data-access/tsconfig.spec.json
  prisma/migrations/20220917172812_/migration.sql
  prisma/migrations/20220917173519_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  tsconfig.base.json
Labels: Priority: High, Status: Busy, Type: Feature, Status: Not-ready

#327 Feature/office maker walls
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/directives/draggable.directive.ts
  apps/office-booker/src/app/directives/drawable.directive.spec.ts
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/directives/droppable.directive.spec.ts
  apps/office-booker/src/app/directives/droppable.directive.ts
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/svg.service.ts
  apps/office-booker/src/favicon.ico
Labels: Type: Enhance, Priority: High, Status: Busy, Type: Change, Type: Feature, Type: Fix

#328 Added snapping to desks on office-maker
  apps/office-booker/src/app/directives/droppable.directive.ts
Labels: Priority: Low, Status: Busy, Type: Feature, Type: Fix

#329 Feature/create map new floor
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/office-maker.service.ts
Labels: Type: Enhance, Priority: High, Status: Needs-tests

#319 Changes across multiple pages
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/styles.css
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
Labels: Priority: Medium, Type: Cosmetic, Type: Feature, Status: Not-ready

#331 Feature/docker pipeline
  .github/workflows/docker.yml
Labels: Priority: High, Status: Busy, Type: Feature

#334 Testing
  prisma/seed.ts
Labels: Priority: Medium, Type: Test, Status: Ready

#336 fix backend image building
  .github/workflows/docker.yml
Labels: Priority: High, Type: Fix, Status: Ready

#338 Feature/live update
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: High, Type: Feature, Status: Ready

#333 Css on create office
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/directives/draggable.directive.spec.ts
  apps/office-booker/src/app/directives/draggable.directive.ts
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.css
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.html
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.spec.ts
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.spec.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.ts
Labels: Priority: High, Type: Cosmetic, Status: Ready

#339 Stopped data leaks with the live update
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Type: Bug, Priority: Medium, Status: Ready

#341 fix bug with facilities saving and css for selected button
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.css
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Type: Bug, Priority: Medium, Type: Cosmetic, Status: Not-ready

#343 Fix/map issues
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/office-maker.service.ts
Labels: Type: Enhance, Priority: High, Status: Needs-tests

#344 Bugfixes
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
Labels: Type: Bug, Priority: Medium, Status: On-hold

#345 Fix/filter
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/authentication/guest-login/guest-login.component.ts
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/directives/draggable.directive.ts
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/services/office-maker.service.ts
  apps/office-booker/src/app/services/svg.service.ts
  libs/api/authorization/src/lib/jwt.strategy.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.spec.ts
  libs/api/permissions/src/lib/api-permissions.service.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
Labels: Priority: Medium, Type: Fix, Status: Needs-tests

#346 add http post to pipeline, to update the running containers
  .github/workflows/docker.yml
Labels: Priority: High, Type: Feature, Status: Ready

#347 prevent false alarm on update pipeline step
  .github/workflows/docker.yml
Labels: Priority: High, Type: Fix, Status: Ready

#349 Fixed email service
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  libs/api/mail/src/lib/mail.module.ts
  libs/api/mail/src/lib/mail.service.ts
Labels: Priority: High, Type: Fix, Status: Ready

#352 Feature/change user name
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
Labels: Type: Enhance, Priority: High, Status: Ready

#354 Fix/backend code smells
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/client.ts
  libs/api/bookings/repository/data-access/src/functions.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  libs/api/bookings/repository/data-access/src/singleton.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.spec.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.spec.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.spec.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.spec.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.spec.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  libs/api/walls/api/src/lib/api-walls-api.controller.ts
Labels: Priority: Low, Status: Busy, Type: Chore

#337 Testing
  .github/workflows/index.yml
  .github/workflows/nxtest.yml
  apps/office-booker/src/app/authentication/login/login.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/environments/environment.prod.ts
  apps/office-booker/src/environments/environment.ts
  libs/api/bookings/api/jest.config.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/bookings/repository/data-access/jest.config.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/companies/api/jest.config.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.spec.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
  libs/api/companies/repository/data-access/jest.config.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.spec.ts
  libs/api/context.ts
  libs/api/desks/api/jest.config.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.spec.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/jest.config.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.spec.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
  libs/api/facilities/api/jest.config.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.spec.ts
  libs/api/facilities/repository/data-access/jest.config.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
  libs/api/permissions/src/lib/api-permissions.service.ts
  libs/api/rooms/api/jest.config.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.spec.ts
  libs/api/rooms/repository/data-access/jest.config.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.spec.ts
  libs/api/users/api/jest.config.ts
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/jest.config.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  libs/api/walls/api/src/lib/api-walls-api.controller.spec.ts
  libs/api/walls/data-access/src/lib/api-walls-data-access.service.spec.ts
Labels: Priority: High, Type: Test, Status: Not-ready

#356 Update environment.prod.ts
  apps/office-booker/src/environments/environment.prod.ts
Labels: Type: Bug, Priority: High, Type: Fix, Status: Ready

#355 Addition/get walls
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/services/office-maker.service.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
  prisma/seed.ts
Labels: Type: Enhance, Priority: Low, Status: Needs-tests

#350 changes suggested by mentors
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/account/account.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/landing-page/landing-page.component.html
  apps/office-booker/src/app/office-maker/new-floor-dialog/new-floor-dialog.component.css
  apps/office-booker/src/app/office-maker/new-floor-dialog/new-floor-dialog.component.html
  apps/office-booker/src/app/office-maker/new-floor-dialog/new-floor-dialog.component.spec.ts
  apps/office-booker/src/app/office-maker/new-floor-dialog/new-floor-dialog.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.css
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/services/office-maker.service.ts
  apps/office-booker/src/assets/office-booker-logo.png
  apps/office-booker/src/favicon.ico
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.ts
  libs/api/rooms/repository/data-access/src/lib/api-rooms-repository-data-access.service.ts
Labels: Type: Bug, Priority: High, Type: Cosmetic, Type: Fix, Status: Ready

#359 Enable live reload temporarily for demo
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Type: Change, Status: Ready

#360 Fix wall create bug, create new facilities
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/office-maker/edit-dialog/edit-dialog.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/services/office-maker.service.ts
  apps/office-booker/src/environments/environment.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.spec.ts
  libs/api/facilities/repository/data-access/src/lib/api-facilities-repository-data-access.service.ts
Labels: Type: Bug, Priority: High, Type: Feature, Status: Ready

#362 Cascade desk deletion
  prisma/migrations/20220929081545_init/migration.sql
  prisma/schema.prisma
Labels: Priority: High, Type: Fix, Status: Ready

#363 fixed buttons being clicked at same time
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/landing-page/landing-page.component.css
  apps/office-booker/src/app/landing-page/landing-page.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
Labels: Type: Bug, Priority: High, Status: Not-ready

#358 Testing
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.spec.ts
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/booking-service.service.spec.ts
  apps/office-booker/src/app/services/office-maker.service.spec.ts
  libs/api/walls/api/src/lib/api-walls-api.controller.spec.ts
  libs/api/walls/data-access/jest.config.ts
  libs/api/walls/data-access/src/lib/api-walls-data-access.service.spec.ts
Labels: Priority: High, Status: Busy, Type: Test

#364 Cascade booking deletion to invites
  prisma/migrations/20220929183435_booking_cascade/migration.sql
  prisma/schema.prisma
Labels: Priority: High, Type: Fix, Status: Ready

#365 Change/fixes map
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Low, Type: Fix, Status: Needs-tests

#357 Prevent duplicate ratings on bookings
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.html
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  docker-compose.yml
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.spec.ts
  libs/api/bookings/repository/data-access/src/lib/api-bookings-repository-data-access.service.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
  prisma/migrations/20220928171312_init/migration.sql
  prisma/schema.prisma
Labels: Priority: Medium, Type: Feature, Status: Needs-info

#366 🐛(sonar): fix for sonar cloud bugs
  apps/office-booker/src/app/authentication/account/account.component.css
  apps/office-booker/src/app/authentication/guest-login/guest-login.component.css
  apps/office-booker/src/app/authentication/guest/guest.component.css
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.css
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/invite-dialog/invite-dialog.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Change, Status: Needs-tests

#367 changed I tag to span tag
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Low, Type: Fix, Status: Ready

#368 fixed slider for voting
  apps/office-booker/src/app/bookings/voting-bookings/voting-bookings.component.ts
Labels: Type: Bug, Priority: High, Status: Ready

#369 Tests for registration component
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/office-maker/office-maker.component.spec.ts
Labels: Priority: High, Status: Busy, Type: Test

#372 Remove secrets
  .env
  .gitignore
Labels: Priority: High, Type: Fix, Status: Ready

#370 🐛(id): duplicate ids being made
  apps/office-booker/src/app/office-maker/office-maker.component.ts
Labels: Priority: Low, Type: Fix, Status: Needs-tests

#373 Update testing to use database from secret
  .github/workflows/nxtest.yml
Labels: Priority: High, Type: Fix, Status: Ready

#376 Testing
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.spec.ts
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
Labels: Priority: High, Status: Busy, Type: Test

#384 ensure affected test also has access to env
  .github/workflows/nxtest.yml
Labels: Priority: High, Type: Fix, Status: Ready

#385 Tests for map bookings
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
Labels: Priority: High, Status: Busy, Type: Test

#386 Testing
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
Labels: Priority: High, Status: Busy, Type: Test

#387 Update README.md
  README.md
Labels: Type: Documentation, Priority: Medium, Status: Ready

#388 Update README.md
  README.md
Labels: Type: Documentation, Priority: High, Status: Ready

#389 quick update on registration page
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
Labels: Type: Bug, Priority: High, Status: Ready
