Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-06, with the labels that each got.

#128 updated picture sizes
  README.md
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#131 Add an email field to user/employee
  libs/api/users/api/src/lib/api-users-api.controller.ts
  prisma/migrations/20220602141457_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Type: Enhance, Priority: High, Type: Change, Status: Ready

#127 Feature/login-page and registration
  angular.json
  apps/office-booker/src/app/app.component.ts
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.spec.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.css
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.html
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.spec.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.spec.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  apps/office-booker/src/environments/environment.prod.ts
  apps/office-booker/src/environments/environment.ts
  tsconfig.base.json
Labels: Priority: Medium, Type: Feature, Status: Ready

#132 Feature/booking card api
  apps/office-booker/src/app/bookings/personal-bookings/booking-card/booking-card.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Priority: Medium, Type: Feature, Status: Ready

#136 Add api endpoint to get user by email
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.ts
Labels: Priority: High, Type: Feature, Status: Ready

#137 Finished backend unit tests
  libs/api/companies/api/src/lib/api-companies-api.controller.spec.ts
  libs/api/companies/repository/data-access/src/lib/api-companies-repository-data-access.service.spec.ts
Labels: Priority: Medium, Type: Chore, Type: Test, Status: Ready

#138 Fix user by email endpoint to use post request
  libs/api/users/api/src/lib/api-users-api.controller.ts
Labels: Priority: High, Type: Fix, Status: Ready

#140 Feature/personal bookings
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
Labels: Priority: High, Type: Feature, Status: Ready

#141 🚧 (component): Adding component
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
Labels: Type: Enhance, Priority: Low, Status: Not-ready

#142 Feature/admin page
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: High, Type: Feature, Status: Ready

#148 Feature/admin page
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.html
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Priority: Low, Type: Cosmetic, Status: Ready

#145 Styling for pages and authentication changes
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: Medium, Type: Feature, Status: On-hold

#149 Changes/office walls desk sizes
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  prisma/seed.ts
Labels: Type: Enhance, Priority: Medium, Status: Needs-tests

#151 Feature/booking filter date
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
  prisma/seed.ts
Labels: Type: Enhance, Priority: Medium, Status: Needs-tests

#150 Feature/companies register
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/services/booking-service.service.ts
Labels: Type: Enhance, Priority: High, Status: Ready

#153 Feature/hiding book
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
Labels: Type: Enhance, Priority: Medium, Type: Feature, Status: Ready

#156 Add JWT checking and validation
  .env
  angular.json
  apps/api/src/app/app.module.ts
  apps/api/src/main.ts
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/cognito.service.ts
  libs/api/authorization/.eslintrc.json
  libs/api/authorization/README.md
  libs/api/authorization/jest.config.ts
  libs/api/authorization/project.json
  libs/api/authorization/src/index.ts
  libs/api/authorization/src/lib/api-authorization.module.ts
  libs/api/authorization/src/lib/auth.config.ts
  libs/api/authorization/src/lib/auth.guard.ts
  libs/api/authorization/src/lib/jwt.strategy.ts
  libs/api/authorization/tsconfig.json
  libs/api/authorization/tsconfig.lib.json
  libs/api/authorization/tsconfig.spec.json
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/facilities/api/src/lib/api-facilities-api.controller.ts
  libs/api/rooms/api/src/lib/api-rooms-api.controller.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
  libs/api/users/repository/data-access/src/lib/api-users-repository-data-access.service.spec.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Priority: High, Type: Feature, Status: Ready

#157 moved members
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#158 nav-bar works with permissions from user
  apps/office-booker/src/app/app.component.ts
  apps/office-booker/src/app/authentication/login/login.component.spec.ts
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.spec.ts
  apps/office-booker/src/app/authentication/sign-out/sign-out.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.spec.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
  apps/office-booker/src/app/cognito.service.ts
  apps/office-booker/src/app/services/booking-service.service.ts
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Priority: High, Type: Feature, Status: Ready

#161 Styling for pages
  apps/office-booker/src/app/app.module.ts
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/assets/background-image.png
  apps/office-booker/src/styles.css
  libs/api/companies/api/src/lib/api-companies-api.controller.ts
Labels: Priority: Medium, Type: Cosmetic, Status: Ready

#163 Add a basic permission service
  angular.json
  apps/api/src/app/app.module.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.spec.ts
  libs/api/bookings/api/src/lib/api-bookings-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
  libs/api/permissions/.eslintrc.json
  libs/api/permissions/README.md
  libs/api/permissions/jest.config.ts
  libs/api/permissions/project.json
  libs/api/permissions/src/index.ts
  libs/api/permissions/src/lib/api-permissions.module.ts
  libs/api/permissions/src/lib/api-permissions.service.spec.ts
  libs/api/permissions/src/lib/api-permissions.service.ts
  libs/api/permissions/tsconfig.json
  libs/api/permissions/tsconfig.lib.json
  libs/api/permissions/tsconfig.spec.json
  prisma/migrations/20220609104623_init/migration.sql
  prisma/schema.prisma
  tsconfig.base.json
Labels: Priority: Medium, Type: Feature, Status: Ready

#164 fix coverage report creation
  jest.preset.ts
Labels: Priority: High, Type: Fix, Status: Ready

#165 Update README.md
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#169 🐛 (bookings): overlap with exact times
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.ts
Labels: Priority: Medium, Type: Fix, Status: Needs-tests

#171 💄 (size): minor size changing for map page
  apps/office-booker/src/app/bookings/map-bookings/map-bookings.component.css
Labels: Priority: Low, Type: Cosmetic, Status: Needs-tests

#174 Update README.md
  README.md
Labels: Type: Documentation, Priority: Medium, Status: Ready

#173 styling and errors messages for login/registration
  apps/office-booker/src/app/authentication/login/login.component.css
  apps/office-booker/src/app/authentication/login/login.component.html
  apps/office-booker/src/app/authentication/login/login.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.css
  apps/office-booker/src/app/authentication/registration/registration.component.html
  apps/office-booker/src/app/authentication/registration/registration.component.ts
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.css
Labels: Priority: High, Type: Cosmetic, Status: Ready

#180 Update README.md
  README.md
Labels: Type: Documentation, Priority: Medium, Status: Ready

#182 Update README.md
  README.md
Labels: Priority: Medium, Status: Busy, Type: Cosmetic
