Repository COS301-SE-2022/Office-Booker, pull requests merged in 2022-10, with the labels that each got.

#391 Cosmetic enhancements
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.css
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
  apps/office-booker/src/assets/fonts/Maven_Pro/MavenPro-VariableFont_wght.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/OFL.txt
  apps/office-booker/src/assets/fonts/Maven_Pro/README.txt
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-Black.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-Bold.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-ExtraBold.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-Medium.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-Regular.ttf
  apps/office-booker/src/assets/fonts/Maven_Pro/static/MavenPro-SemiBold.ttf
  apps/office-booker/src/styles.css
Labels: Priority: Low, Status: Busy, Type: Cosmetic

#397 Email service fix
  apps/office-booker/src/app/authentication/invite-guest/invite-guest.component.ts
  apps/office-booker/src/app/authentication/registration/registration.component.spec.ts
  libs/api/mail/src/lib/mail.module.ts
  libs/api/users/api/src/lib/api-users-api.controller.spec.ts
  libs/api/users/api/src/lib/api-users-api.controller.ts
Labels: Priority: High, Type: Fix, Status: Ready

#400 Update README.md
  README.md
Labels: Type: Documentation, Priority: Medium, Status: Ready

#399 cascade booking delete to bookingvotedon
  prisma/migrations/20220917173519_init/migration.sql
  prisma/migrations/20220928171312_init/migration.sql
  prisma/migrations/20220929081545_init/migration.sql
  prisma/migrations/20220929183435_booking_cascade/migration.sql
  prisma/migrations/20221023175612_/migration.sql
  prisma/schema.prisma
Labels: Priority: Medium, Type: Fix, Status: Ready

#401 Create desk with attributes
  libs/api/desks/api/src/lib/api-desks-api.controller.ts
  libs/api/desks/repository/data-access/src/lib/api-desks-repository-data-access.service.ts
Labels: Type: Enhance, Priority: Low, Status: Ready

#402 Create README.md
  README.md
Labels: Type: Documentation, Priority: Low, Status: Ready

#403 Update README.md
  README.md
Labels: Type: Documentation, Priority: High, Status: Ready

#405 actually fix booking cascade delete
  prisma/migrations/20221025133545_/migration.sql
  prisma/schema.prisma
Labels: Type: Enhance, Priority: High, Status: Ready

#404 Guests can no longer vote
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
Labels: Priority: High, Type: Fix, Status: Ready

#408 Cosmetic changes
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.css
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.html
  apps/office-booker/src/app/shared/menu-bar/menu-bar.component.ts
Labels: Priority: High, Type: Cosmetic, Status: Ready

#409 admin and personal bookings wont show past bookings anymore
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.ts
  apps/office-booker/src/app/bookings/personal-bookings/personal-bookings.component.ts
Labels: Type: Bug, Priority: Medium, Status: Ready

#412 🐛(facilities): save facilities with create
  apps/office-booker/src/app/office-maker/office-maker.component.ts
  apps/office-booker/src/app/services/office-maker.service.ts
Labels: Priority: Low, Type: Fix, Status: Needs-tests

#413 Removed delete employee button
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
Labels: Priority: High, Type: Change, Status: Ready

#414 fix layout of employee cards on admin page
  .env
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.css
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
Labels: Priority: High, Type: Cosmetic, Status: Ready

#416 Fix/minor changes
  apps/office-booker/src/app/bookings/admin-bookings/admin-bookings.component.html
  apps/office-booker/src/app/bookings/map-bookings/desk-popup/desk-popup.component.html
  apps/office-booker/src/app/directives/drawable.directive.ts
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
Labels: Type: Enhance, Priority: High, Status: Ready

#417 Fix/office maker draw walls
  apps/office-booker/src/app/office-maker/office-maker.component.html
  apps/office-booker/src/app/office-maker/office-maker.component.ts
Labels: Type: Enhance, Priority: High, Type: Fix, Status: Ready

#418 update readme to reflect team member's roles
  README.md
Labels: Type: Documentation, Priority: High, Status: Ready
